//===- OpDocGen.cpp - MLIR operation documentation generator --------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// OpDocGen uses the description of operations to generate documentation for the
// operations.
//
//===----------------------------------------------------------------------===//

#include "DialectGenUtilities.h"
#include "DocGenUtilities.h"
#include "OpGenHelpers.h"
#include "mlir/Support/IndentedOstream.h"
#include "mlir/TableGen/AttrOrTypeDef.h"
#include "mlir/TableGen/Attribute.h"
#include "mlir/TableGen/EnumInfo.h"
#include "mlir/TableGen/GenInfo.h"
#include "mlir/TableGen/Operator.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/Signals.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
#include "llvm/TableGen/TableGenBackend.h"

#include <set>
#include <string>

using namespace llvm;
using namespace mlir;
using namespace mlir::tblgen;
using mlir::tblgen::Operator;

//===----------------------------------------------------------------------===//
// Commandline Options
//===----------------------------------------------------------------------===//
static cl::OptionCategory
    docCat("Options for -gen-(attrdef|typedef|enum|op|dialect)-doc");
static cl::opt<std::string>
    stripPrefix("strip-prefix",
                cl::desc("Strip prefix of the fully qualified names"),
                cl::init("::mlir::"), cl::cat(docCat));
static cl::opt<bool> allowHugoSpecificFeatures(
    "allow-hugo-specific-features",
    cl::desc("Allows using features specific to Hugo"), cl::init(false),
    cl::cat(docCat));
static cl::opt<bool>
    keepOpSourceOrder("keep-op-source-order",
                      cl::desc("Do not sort ops alphabetically"),
                      cl::init(false), cl::cat(docCat));
static cl::opt<bool> emitRst("rst", cl::desc("Emit reStructuredText output"),
                             cl::init(false), cl::cat(docCat));

namespace {
/// Abstract base class providing hooks for generating document elements in a
/// specific format (Markdown or reStructuredText).
class DocumentFormat {
public:
  virtual ~DocumentFormat() = default;

  /// Emit an auto-generated file comment/preamble.
  virtual void emitAutoGenComment(raw_ostream &os) = 0;

  /// Emit a heading at the given level (1 = top-level, 2 = section, etc.).
  virtual void emitHeading(unsigned level, StringRef text, raw_ostream &os) = 0;

  /// Emit an emphasized summary line (e.g. italic).
  virtual void emitSummary(StringRef summary, raw_ostream &os) = 0;

  /// Emit an inline code span.
  virtual std::string inlineCode(StringRef text) = 0;

  /// Emit unnamed placeholder text (for unnamed operands, etc.).
  virtual void emitUnnamedPlaceholder(raw_ostream &os) = 0;

  /// Emit a named constraint row in a table.
  template <typename T>
  void emitNamedConstraintRow(const T &it, raw_ostream &os) {
    if (!it.name.empty())
      emitNamedConstraintRowImpl(it.name, it.constraint.getSummary(), os);
    else
      emitUnnamedConstraintRowImpl(it.constraint.getSummary(), os);
  }

  /// Emit the start of a fenced code block.
  virtual void emitCodeBlockStart(raw_ostream &os, StringRef language = "") = 0;

  /// Emit the end of a fenced code block.
  virtual void emitCodeBlockEnd(raw_ostream &os) = 0;

  /// Emit a hyperlink.
  virtual void emitLink(StringRef text, StringRef url, raw_ostream &os) = 0;

  /// Emit a TOC marker.
  virtual void emitTocMarker(raw_ostream &os) = 0;

  /// Check whether the description already contains a TOC marker.
  virtual bool hasTocMarker(StringRef description) = 0;

  /// Emit a simple two-column table header.
  virtual void emitTableHeader(ArrayRef<StringRef> columns,
                               raw_ostream &os) = 0;

  /// Emit a simple table row with values matching the header columns.
  virtual void emitTableRow(ArrayRef<const std::string> values,
                            raw_ostream &os) = 0;

  /// Emit the start of the attribute table (may use HTML for Markdown).
  virtual void emitAttrTableStart(raw_ostream &os) = 0;

  /// Emit an attribute table row.
  virtual void emitAttrTableRow(StringRef name, StringRef storageType,
                                StringRef summary, StringRef description,
                                bool allowHugo, raw_ostream &os) = 0;

  /// Emit the end of the attribute table.
  virtual void emitAttrTableEnd(raw_ostream &os) = 0;

  /// Takes content generated by `fn` and nests all headings one level deeper
  /// if `nest` is true.
  virtual void nestHeadings(bool nest,
                            llvm::function_ref<void(raw_ostream &os)> fn,
                            raw_ostream &os) = 0;

  /// Emit a comma-separated list of items with a label prefix.
  virtual void emitLabeledList(StringRef label,
                               const std::set<std::string> &items,
                               raw_ostream &os) = 0;

protected:
  virtual void emitNamedConstraintRowImpl(StringRef name, StringRef summary,
                                          raw_ostream &os) = 0;
  virtual void emitUnnamedConstraintRowImpl(StringRef summary,
                                            raw_ostream &os) = 0;
};

//===----------------------------------------------------------------------===//
// Markdown Format
//===----------------------------------------------------------------------===//

class MarkdownFormat : public DocumentFormat {
public:
  void emitAutoGenComment(raw_ostream &os) override {
    os << "<!-- Autogenerated by mlir-tblgen; don't manually edit -->\n";
  }

  void emitHeading(unsigned level, StringRef text, raw_ostream &os) override {
    os << "\n";
    for (unsigned i = 0; i < level; ++i)
      os << "#";
    os << " " << text << "\n";
  }

  void emitSummary(StringRef summary, raw_ostream &os) override {
    if (summary.empty())
      return;
    StringRef trimmed = summary.trim();
    char first = std::toupper(trimmed.front());
    StringRef rest = trimmed.drop_front();
    os << "\n_" << first << rest << "_\n";
  }

  std::string inlineCode(StringRef text) override {
    return ("`" + text + "`").str();
  }

  void emitUnnamedPlaceholder(raw_ostream &os) override {
    os << "&laquo;unnamed&raquo;";
  }

  void emitCodeBlockStart(raw_ostream &os, StringRef language) override {
    os << "```";
    if (!language.empty())
      os << language;
    os << "\n";
  }

  void emitCodeBlockEnd(raw_ostream &os) override { os << "```\n"; }

  void emitLink(StringRef text, StringRef url, raw_ostream &os) override {
    os << "[" << text << "](" << url << ")";
  }

  void emitTocMarker(raw_ostream &os) override { os << "\n[TOC]\n"; }

  bool hasTocMarker(StringRef description) override {
    Regex r("^[[:space:]]*\\[TOC\\]$", Regex::RegexFlags::Newline);
    return r.match(description);
  }

  void emitTableHeader(ArrayRef<StringRef> columns, raw_ostream &os) override {
    os << "|";
    for (StringRef col : columns)
      os << " " << col << " |";
    os << "\n|";
    for (size_t i = 0; i < columns.size(); ++i) {
      size_t width = columns[i].size();
      if (width < 3)
        width = 3;
      // First column is centered, last column is left-aligned, others centered.
      if (i < columns.size() - 1) {
        os << " :";
        for (size_t j = 0; j < width - 2; ++j)
          os << "-";
        os << ": |";
      } else {
        os << " ";
        for (size_t j = 0; j < width; ++j)
          os << "-";
        os << " |";
      }
    }
    os << "\n";
  }

  void emitTableRow(ArrayRef<const std::string> values,
                    raw_ostream &os) override {
    os << "|";
    for (const std::string &val : values)
      os << " " << val << " |";
    os << "\n";
  }

  void emitAttrTableStart(raw_ostream &os) override {
    os << "<table>\n";
    os << "<tr><th>Attribute</th><th>MLIR Type</th><th>Description</th></tr>"
          "\n";
  }

  void emitAttrTableRow(StringRef name, StringRef storageType,
                        StringRef summary, StringRef description,
                        bool allowHugo, raw_ostream &os) override {
    os << "<tr>";
    os << "<td><code>" << name << "</code></td><td>" << storageType
       << "</td><td>";
    if (allowHugo && !description.empty()) {
      os << "<details>" << "<summary>" << summary << "</summary>"
         << "{{% markdown %}}" << description << "{{% /markdown %}}"
         << "</details>";
    } else {
      os << summary;
    }
    os << "</td></tr>\n";
  }

  void emitAttrTableEnd(raw_ostream &os) override { os << "</table>\n"; }

  void nestHeadings(bool nest, llvm::function_ref<void(raw_ostream &os)> fn,
                    raw_ostream &os) override {
    std::string str;
    raw_string_ostream ss(str);
    fn(ss);
    for (StringRef x : llvm::split(str, "\n")) {
      if (nest && x.starts_with("#"))
        os << "#";
      os << x << "\n";
    }
  }

  void emitLabeledList(StringRef label, const std::set<std::string> &items,
                       raw_ostream &os) override {
    interleaveComma(items, os << "\n" << label << ": ");
    os << "\n";
  }

protected:
  void emitNamedConstraintRowImpl(StringRef name, StringRef summary,
                                  raw_ostream &os) override {
    os << "| `" << name << "` | " << summary << " |\n";
  }

  void emitUnnamedConstraintRowImpl(StringRef summary,
                                    raw_ostream &os) override {
    os << "| &laquo;unnamed&raquo; | " << summary << " |\n";
  }
};

//===----------------------------------------------------------------------===//
// reStructuredText Format
//===----------------------------------------------------------------------===//

class ReStructuredTextFormat : public DocumentFormat {
public:
  void emitAutoGenComment(raw_ostream &os) override {
    os << ".. Autogenerated by mlir-tblgen; don't manually edit\n\n";
  }

  void emitHeading(unsigned level, StringRef text, raw_ostream &os) override {
    // RST heading underline characters by level.
    static const char underlines[] = {'=', '-', '~', '^', '"'};
    unsigned idx = (level > 0 ? level - 1 : 0);
    if (idx >= sizeof(underlines))
      idx = sizeof(underlines) - 1;
    os << "\n" << text << "\n";
    for (size_t i = 0, e = text.size(); i < e; ++i)
      os << underlines[idx];
    os << "\n";
  }

  void emitSummary(StringRef summary, raw_ostream &os) override {
    if (summary.empty())
      return;
    StringRef trimmed = summary.trim();
    char first = std::toupper(trimmed.front());
    StringRef rest = trimmed.drop_front();
    os << "\n*" << first << rest << "*\n";
  }

  std::string inlineCode(StringRef text) override {
    return ("``" + text + "``").str();
  }

  void emitUnnamedPlaceholder(raw_ostream &os) override { os << "*unnamed*"; }

  void emitCodeBlockStart(raw_ostream &os, StringRef language) override {
    os << ".. code-block::";
    if (!language.empty())
      os << " " << language;
    os << "\n\n";
  }

  void emitCodeBlockEnd(raw_ostream &os) override {
    // No explicit end marker in RST; just a blank line ends the block.
    os << "\n";
  }

  void emitLink(StringRef text, StringRef url, raw_ostream &os) override {
    os << "`" << text << " <" << url << ">`_";
  }

  void emitTocMarker(raw_ostream &os) override {
    os << "\n.. contents::\n   :local:\n";
  }

  bool hasTocMarker(StringRef description) override {
    return description.contains(".. contents::");
  }

  void emitTableHeader(ArrayRef<StringRef> columns, raw_ostream &os) override {
    // Use RST list-table directive.
    os << ".. list-table::\n";
    os << "   :header-rows: 1\n\n";
    os << "   * ";
    for (size_t i = 0; i < columns.size(); ++i) {
      if (i > 0)
        os << "     ";
      os << "- " << columns[i] << "\n";
    }
  }

  void emitTableRow(ArrayRef<const std::string> values,
                    raw_ostream &os) override {
    os << "   * ";
    for (size_t i = 0; i < values.size(); ++i) {
      if (i > 0)
        os << "     ";
      os << "- " << values[i] << "\n";
    }
  }

  void emitAttrTableStart(raw_ostream &os) override {
    os << ".. list-table::\n";
    os << "   :header-rows: 1\n\n";
    os << "   * - Attribute\n";
    os << "     - MLIR Type\n";
    os << "     - Description\n";
  }

  void emitAttrTableRow(StringRef name, StringRef storageType,
                        StringRef summary, StringRef description,
                        bool allowHugo, raw_ostream &os) override {
    (void)allowHugo; // Hugo features not applicable in RST.
    os << "   * - ``" << name << "``\n";
    os << "     - " << storageType << "\n";
    os << "     - " << summary << "\n";
  }

  void emitAttrTableEnd(raw_ostream &os) override {
    // No explicit end needed for list-table.
  }

  void nestHeadings(bool nest, llvm::function_ref<void(raw_ostream &os)> fn,
                    raw_ostream &os) override {
    // In RST, heading levels are determined by underline characters. When
    // nesting, we shift each underline character one level deeper.
    std::string str;
    raw_string_ostream ss(str);
    fn(ss);
    if (!nest) {
      os << str;
      return;
    }
    static const char underlines[] = {'=', '-', '~', '^', '"'};
    for (StringRef line : llvm::split(str, "\n")) {
      if (!line.empty() && line.find_first_not_of(line[0]) == StringRef::npos) {
        char ch = line[0];
        // Check if this is an underline line.
        bool isUnderline = false;
        for (char u : underlines) {
          if (ch == u) {
            isUnderline = true;
            break;
          }
        }
        if (isUnderline) {
          // Shift to next level.
          char newCh = ch;
          for (unsigned i = 0; i < sizeof(underlines) - 1; ++i) {
            if (underlines[i] == ch) {
              newCh = underlines[i + 1];
              break;
            }
          }
          for (size_t i = 0, e = line.size(); i < e; ++i)
            os << newCh;
          os << "\n";
          continue;
        }
      }
      os << line << "\n";
    }
  }

  void emitLabeledList(StringRef label, const std::set<std::string> &items,
                       raw_ostream &os) override {
    interleaveComma(items, os << "\n" << label << ": ");
    os << "\n";
  }

protected:
  void emitNamedConstraintRowImpl(StringRef name, StringRef summary,
                                  raw_ostream &os) override {
    os << "   * - ``" << name << "``\n";
    os << "     - " << summary << "\n";
  }

  void emitUnnamedConstraintRowImpl(StringRef summary,
                                    raw_ostream &os) override {
    os << "   * - *unnamed*\n";
    os << "     - " << summary << "\n";
  }
};

/// Return the DocumentFormat instance to use based on the --rst flag.
static DocumentFormat &getDocumentFormat() {
  static std::unique_ptr<DocumentFormat> format =
      []() -> std::unique_ptr<DocumentFormat> {
    if (emitRst)
      return std::make_unique<ReStructuredTextFormat>();
    return std::make_unique<MarkdownFormat>();
  }();
  return *format;
}
} // namespace

void mlir::tblgen::emitSummary(StringRef summary, raw_ostream &os) {
  if (summary.empty())
    return;
  StringRef trimmed = summary.trim();
  char first = std::toupper(trimmed.front());
  StringRef rest = trimmed.drop_front();
  os << "\n_" << first << rest << "_\n";
}

// Emit the description by aligning the text to the left per line (e.g.,
// removing the minimum indentation across the block).
//
// This expects that the description in the tablegen file is already formatted
// in a way the user wanted but has some additional indenting due to being
// nested in the op definition.
void mlir::tblgen::emitDescription(StringRef description, raw_ostream &os) {
  if (description.empty())
    return;
  os << "\n";
  raw_indented_ostream ros(os);
  StringRef trimmed = description.rtrim(" \t");
  ros.printReindented(trimmed);
  if (!trimmed.ends_with("\n"))
    ros << "\n";
}

void mlir::tblgen::emitDescriptionComment(StringRef description,
                                          raw_ostream &os, StringRef prefix) {
  if (description.empty())
    return;
  os << "\n";
  raw_indented_ostream ros(os);
  StringRef trimmed = description.rtrim(" \t");
  ros.printReindented(trimmed, (Twine(prefix) + "/// ").str());
  if (!trimmed.ends_with("\n"))
    ros << "\n";
}

//===----------------------------------------------------------------------===//
// Records
//===----------------------------------------------------------------------===//

namespace {
struct OpDocGroup {
  const Dialect &getDialect() const { return ops.front().getDialect(); }

  /// Summary description of the section.
  std::string summary = "";

  /// Description of the section.
  StringRef description = "";

  /// Instances inside the section.
  std::vector<Operator> ops;
};

/// Holds all records collected from a dialect relevant for documentation
/// generation.
struct DialectRecords {
  DialectRecords(Dialect dialect, StringRef inputFilename)
      : dialect(dialect), inputFilename(inputFilename) {}

  Dialect dialect;
  StringRef inputFilename;
  std::vector<Attribute> attributes;
  std::vector<AttrDef> attrDefs;
  std::vector<OpDocGroup> ops;
  std::vector<Type> types;
  std::vector<TypeDef> typeDefs;
  std::vector<EnumInfo> enums;
};
} // namespace

//===----------------------------------------------------------------------===//
// Operation Documentation
//===----------------------------------------------------------------------===//

/// Emit the assembly format of an operation.
static void emitAssemblyFormat(StringRef opName, StringRef format,
                               raw_ostream &os) {
  if (format.empty())
    return;
  os << "\nSyntax:\n\n";
  getDocumentFormat().emitCodeBlockStart(os, "");
  os << "operation ::= `" << opName << "` ";

  // Print the assembly format aligned.
  unsigned indent = strlen("operation ::= ");
  std::pair<StringRef, StringRef> split = format.split('\n');
  os << split.first.trim() << "\n";
  do {
    split = split.second.split('\n');
    StringRef formatChunk = split.first.trim();
    if (!formatChunk.empty())
      os.indent(indent) << formatChunk << "\n";
  } while (!split.second.empty());
  getDocumentFormat().emitCodeBlockEnd(os);
}

static void emitOpTraitsDoc(const Operator &op, raw_ostream &os) {
  // TODO: We should link to the trait/documentation of it. That also means we
  // should add descriptions to traits that can be queried.
  // Collect using set to sort effects, interfaces & traits.
  std::set<std::string> effects, interfaces, traits;
  for (auto &trait : op.getTraits()) {
    if (isa<PredTrait>(&trait))
      continue;

    std::string name = trait.getDef().getName().str();
    StringRef ref = name;
    StringRef traitName = trait.getDef().getValueAsString("trait");
    traitName.consume_back("::Trait");
    traitName.consume_back("::Impl");
    if (ref.starts_with("anonymous_"))
      name = traitName.str();
    if (isa<InterfaceTrait>(&trait)) {
      if (trait.getDef().isSubClassOf("SideEffectsTraitBase")) {
        auto effectName = trait.getDef().getValueAsString("baseEffectName");
        effectName.consume_front("::");
        effectName.consume_front("mlir::");
        std::string effectStr;
        raw_string_ostream os(effectStr);
        os << effectName << "{";
        auto list = trait.getDef().getValueAsListOfDefs("effects");
        interleaveComma(list, os, [&](const Record *rec) {
          StringRef effect = rec->getValueAsString("effect");
          effect.consume_front("::");
          effect.consume_front("mlir::");
          os << effect << " on " << rec->getValueAsString("resource");
        });
        os << "}";
        effects.insert(getDocumentFormat().inlineCode(effectStr));
        name.append(formatv(" ({0})", traitName).str());
      }
      interfaces.insert(getDocumentFormat().inlineCode(name));
      continue;
    }

    traits.insert(getDocumentFormat().inlineCode(name));
  }
  if (!traits.empty())
    getDocumentFormat().emitLabeledList("Traits", traits, os);
  if (!interfaces.empty())
    getDocumentFormat().emitLabeledList("Interfaces", interfaces, os);
  if (!effects.empty())
    getDocumentFormat().emitLabeledList("Effects", effects, os);
}

static StringRef resolveAttrDescription(const Attribute &attr) {
  StringRef description = attr.getDescription();
  if (description.empty())
    return attr.getBaseAttr().getDescription();
  return description;
}

static void emitOpDoc(const Operator &op, raw_ostream &os) {
  std::string classNameStr = op.getQualCppClassName();
  StringRef className = classNameStr;
  (void)className.consume_front(stripPrefix);
  std::string heading =
      formatv("{0} ({1})",
              getDocumentFormat().inlineCode(op.getOperationName()), className);
  getDocumentFormat().emitHeading(3, heading, os);

  // Emit the summary, syntax, and description if present.
  if (op.hasSummary())
    getDocumentFormat().emitSummary(op.getSummary(), os);
  if (op.hasAssemblyFormat())
    emitAssemblyFormat(op.getOperationName(), op.getAssemblyFormat().trim(),
                       os);
  if (op.hasDescription())
    mlir::tblgen::emitDescription(op.getDescription(), os);

  emitOpTraitsDoc(op, os);

  // Emit attributes.
  if (op.getNumAttributes() != 0) {
    getDocumentFormat().emitHeading(4, "Attributes:", os);
    os << "\n";
    getDocumentFormat().emitAttrTableStart(os);
    for (const auto &it : op.getAttributes()) {
      StringRef storageType = it.attr.getStorageType();
      StringRef description = resolveAttrDescription(it.attr);
      getDocumentFormat().emitAttrTableRow(it.name, storageType,
                                           it.attr.getSummary(), description,
                                           allowHugoSpecificFeatures, os);
    }
    getDocumentFormat().emitAttrTableEnd(os);
  }

  // Emit each of the operands.
  if (op.getNumOperands() != 0) {
    getDocumentFormat().emitHeading(4, "Operands:", os);
    os << "\n";
    StringRef operandCols[] = {"Operand", "Description"};
    getDocumentFormat().emitTableHeader(operandCols, os);
    for (const auto &it : op.getOperands())
      getDocumentFormat().emitNamedConstraintRow(it, os);
  }

  // Emit results.
  if (op.getNumResults() != 0) {
    getDocumentFormat().emitHeading(4, "Results:", os);
    os << "\n";
    StringRef resultCols[] = {"Result", "Description"};
    getDocumentFormat().emitTableHeader(resultCols, os);
    for (const auto &it : op.getResults())
      getDocumentFormat().emitNamedConstraintRow(it, os);
  }

  // Emit successors.
  if (op.getNumSuccessors() != 0) {
    getDocumentFormat().emitHeading(4, "Successors:", os);
    os << "\n";
    StringRef successorCols[] = {"Successor", "Description"};
    getDocumentFormat().emitTableHeader(successorCols, os);
    for (const auto &it : op.getSuccessors())
      getDocumentFormat().emitNamedConstraintRow(it, os);
  }

  os << "\n";
}

static void emitSourceLink(StringRef inputFilename, raw_ostream &os) {
  size_t pathBegin = inputFilename.find("mlir/include/mlir/");
  if (pathBegin == StringRef::npos)
    return;

  StringRef inputFromMlirInclude = inputFilename.substr(pathBegin);
  std::string url =
      ("https://github.com/llvm/llvm-project/blob/main/" + inputFromMlirInclude)
          .str();
  os << "\n";
  getDocumentFormat().emitLink("source", url, os);
  os << "\n";
}

static void emitOpDocGroup(const OpDocGroup &grouping, raw_ostream &os) {
  bool nested = !grouping.summary.empty();
  getDocumentFormat().nestHeadings(
      nested,
      [&](raw_ostream &os) {
        if (nested) {
          getDocumentFormat().emitHeading(2, StringRef(grouping.summary).trim(),
                                          os);
          emitDescription(grouping.description, os);
          os << "\n";
        }
        for (const Operator &op : grouping.ops) {
          emitOpDoc(op, os);
        }
      },
      os);
}

static bool emitOpDoc(const DialectRecords &records, raw_ostream &os) {
  getDocumentFormat().emitAutoGenComment(os);
  emitSourceLink(records.inputFilename, os);
  for (const OpDocGroup &grouping : records.ops)
    emitOpDocGroup(grouping, os);
  return false;
}

//===----------------------------------------------------------------------===//
// Attribute Documentation
//===----------------------------------------------------------------------===//

static void emitAttrDoc(const Attribute &attr, raw_ostream &os) {
  getDocumentFormat().emitHeading(3, attr.getSummary(), os);
  emitDescription(attr.getDescription(), os);
  os << "\n";
}

//===----------------------------------------------------------------------===//
// Type Documentation
//===----------------------------------------------------------------------===//

static void emitTypeDoc(const Type &type, raw_ostream &os) {
  getDocumentFormat().emitHeading(3, type.getSummary(), os);
  emitDescription(type.getDescription(), os);
  os << "\n";
}

//===----------------------------------------------------------------------===//
// TypeDef Documentation
//===----------------------------------------------------------------------===//

static void emitAttrOrTypeDefAssemblyFormat(const AttrOrTypeDef &def,
                                            raw_ostream &os) {
  ArrayRef<AttrOrTypeParameter> parameters = def.getParameters();
  char prefix = isa<AttrDef>(def) ? '#' : '!';
  if (parameters.empty()) {
    std::string syntax =
        (Twine(prefix) + def.getDialect().getName() + "." + *def.getMnemonic())
            .str();
    os << "\nSyntax: " << getDocumentFormat().inlineCode(syntax) << "\n";
    return;
  }

  os << "\nSyntax:\n\n";
  getDocumentFormat().emitCodeBlockStart(os, "");
  os << prefix << def.getDialect().getName() << "." << def.getMnemonic()
     << "<\n";
  for (const auto &it : llvm::enumerate(parameters)) {
    const AttrOrTypeParameter &param = it.value();
    os << "  " << param.getSyntax();
    if (it.index() < (parameters.size() - 1))
      os << ",";
    os << "   # " << param.getName() << "\n";
  }
  os << ">\n";
  getDocumentFormat().emitCodeBlockEnd(os);
}

static void emitAttrOrTypeDefDoc(const AttrOrTypeDef &def, raw_ostream &os) {
  getDocumentFormat().emitHeading(3, def.getCppClassName(), os);

  // Emit the summary if present.
  if (def.hasSummary())
    getDocumentFormat().emitSummary(def.getSummary(), os);

  // Emit the syntax if present.
  if (def.getMnemonic() && !def.hasCustomAssemblyFormat())
    emitAttrOrTypeDefAssemblyFormat(def, os);

  // Emit the description if present.
  if (def.hasDescription()) {
    mlir::tblgen::emitDescription(def.getDescription(), os);
  }

  // Emit parameter documentation.
  ArrayRef<AttrOrTypeParameter> parameters = def.getParameters();
  if (!parameters.empty()) {
    getDocumentFormat().emitHeading(4, "Parameters:", os);
    os << "\n";
    StringRef paramCols[] = {"Parameter", "C++ type", "Description"};
    getDocumentFormat().emitTableHeader(paramCols, os);
    for (const auto &it : parameters) {
      auto desc = it.getSummary();
      std::string values[] = {it.getName().str(),
                              getDocumentFormat().inlineCode(it.getCppType()),
                              desc ? desc->str() : std::string()};
      getDocumentFormat().emitTableRow(values, os);
    }
  }

  os << "\n";
}

static bool emitAttrDefDoc(const DialectRecords &records, raw_ostream &os) {
  getDocumentFormat().emitAutoGenComment(os);
  for (const AttrDef &def : records.attrDefs)
    emitAttrOrTypeDefDoc(def, os);
  return false;
}

static bool emitTypeDefDoc(const DialectRecords &records, raw_ostream &os) {
  getDocumentFormat().emitAutoGenComment(os);
  for (const TypeDef &def : records.typeDefs)
    emitAttrOrTypeDefDoc(def, os);
  return false;
}

//===----------------------------------------------------------------------===//
// Enum Documentation
//===----------------------------------------------------------------------===//

static void emitEnumDoc(const EnumInfo &def, raw_ostream &os) {
  getDocumentFormat().emitHeading(3, def.getEnumClassName(), os);

  // Emit the summary if present.
  getDocumentFormat().emitSummary(def.getSummary(), os);

  // Emit case documentation.
  std::vector<EnumCase> cases = def.getAllCases();
  getDocumentFormat().emitHeading(4, "Cases:", os);
  os << "\n";
  StringRef enumCols[] = {"Symbol", "Value", "String"};
  getDocumentFormat().emitTableHeader(enumCols, os);
  for (const auto &it : cases) {
    std::string values[] = {
        it.getSymbol().str(),
        getDocumentFormat().inlineCode(std::to_string(it.getValue())),
        it.getStr().str()};
    getDocumentFormat().emitTableRow(values, os);
  }

  os << "\n";
}

static bool emitEnumDoc(const DialectRecords &records, raw_ostream &os) {
  getDocumentFormat().emitAutoGenComment(os);
  for (const EnumInfo &def : records.enums)
    emitEnumDoc(def, os);
  return false;
}

//===----------------------------------------------------------------------===//
// Dialect Documentation
//===----------------------------------------------------------------------===//

static void emitBlock(const DialectRecords &records, raw_ostream &os) {
  if (!records.ops.empty()) {
    getDocumentFormat().emitHeading(2, "Operations", os);
    emitSourceLink(records.inputFilename, os);
    for (const OpDocGroup &grouping : records.ops)
      emitOpDocGroup(grouping, os);
  }

  if (!records.attributes.empty()) {
    getDocumentFormat().emitHeading(2, "Attribute constraints", os);
    for (const Attribute &attr : records.attributes)
      emitAttrDoc(attr, os);
  }

  if (!records.attrDefs.empty()) {
    getDocumentFormat().emitHeading(2, "Attributes", os);
    for (const AttrDef &def : records.attrDefs)
      emitAttrOrTypeDefDoc(def, os);
  }

  // TODO: Add link between use and def for types
  if (!records.types.empty()) {
    getDocumentFormat().emitHeading(2, "Type constraints", os);
    for (const Type &type : records.types)
      emitTypeDoc(type, os);
  }

  if (!records.typeDefs.empty()) {
    getDocumentFormat().emitHeading(2, "Types", os);
    for (const TypeDef &def : records.typeDefs)
      emitAttrOrTypeDefDoc(def, os);
  }

  if (!records.enums.empty()) {
    getDocumentFormat().emitHeading(2, "Enums", os);
    for (const EnumInfo &def : records.enums)
      emitEnumDoc(def, os);
  }
}

static bool emitDialectDoc(const DialectRecords &records, raw_ostream &os) {
  getDocumentFormat().emitAutoGenComment(os);
  std::string dialectHeading =
      ("'" + records.dialect.getName() + "' Dialect").str();
  getDocumentFormat().emitHeading(1, dialectHeading, os);
  getDocumentFormat().emitSummary(records.dialect.getSummary(), os);
  emitDescription(records.dialect.getDescription(), os);

  // Generate a TOC marker except if description already contains one.
  if (!getDocumentFormat().hasTocMarker(records.dialect.getDescription()))
    getDocumentFormat().emitTocMarker(os);

  emitBlock(records, os);
  return false;
}

//===----------------------------------------------------------------------===//
// Record Collection
//===----------------------------------------------------------------------===//

/// Collect, filter, and organize all records relevant for dialect documentation
/// generation. Returns none if no single dialect could be determined. See
/// `mlir::tblgen::findDialectToGenerate`.
static std::optional<DialectRecords>
collectRecords(const RecordKeeper &records) {
  auto dialectDefs = records.getAllDerivedDefinitionsIfDefined("Dialect");
  SmallVector<Dialect> dialects(dialectDefs.begin(), dialectDefs.end());
  std::optional<Dialect> dialect = findDialectToGenerate(dialects);
  if (!dialect)
    return std::nullopt;

  std::vector<const Record *> opDefs = getRequestedOpDefinitions(records);
  auto attrDefs = records.getAllDerivedDefinitionsIfDefined("DialectAttr");
  auto typeDefs = records.getAllDerivedDefinitionsIfDefined("DialectType");
  auto typeDefDefs = records.getAllDerivedDefinitionsIfDefined("TypeDef");
  auto attrDefDefs = records.getAllDerivedDefinitionsIfDefined("AttrDef");
  auto enumDefs = records.getAllDerivedDefinitionsIfDefined("EnumInfo");

  DialectRecords result(*dialect, records.getInputFilename());
  SmallDenseSet<const Record *> seen;
  auto addIfNotSeen = [&](const Record *record, const auto &def, auto &vec) {
    if (seen.insert(record).second) {
      vec.push_back(def);
      return true;
    }
    return false;
  };
  auto addIfInDialect = [&](const Record *record, const auto &def, auto &vec) {
    return def.getDialect() == *dialect && addIfNotSeen(record, def, vec);
  };

  SmallDenseMap<const Record *, OpDocGroup> opDocGroup;

  for (const Record *def : attrDefDefs)
    addIfInDialect(def, AttrDef(def), result.attrDefs);
  for (const Record *def : attrDefs)
    addIfInDialect(def, Attribute(def), result.attributes);
  for (const Record *def : opDefs) {
    if (const Record *group = def->getValueAsOptionalDef("opDocGroup")) {
      OpDocGroup &op = opDocGroup[group];
      addIfInDialect(def, Operator(def), op.ops);
    } else {
      OpDocGroup op;
      op.ops.emplace_back(def);
      addIfInDialect(def, op, result.ops);
    }
  }
  for (const Record *rec :
       records.getAllDerivedDefinitionsIfDefined("OpDocGroup")) {
    if (opDocGroup[rec].ops.empty())
      continue;
    opDocGroup[rec].summary = rec->getValueAsString("summary");
    opDocGroup[rec].description = rec->getValueAsString("description");
    result.ops.push_back(opDocGroup[rec]);
  }
  for (const Record *def : typeDefDefs)
    addIfInDialect(def, TypeDef(def), result.typeDefs);
  for (const Record *def : typeDefs)
    addIfInDialect(def, Type(def), result.types);
  result.enums.reserve(enumDefs.size());
  for (const Record *def : enumDefs)
    addIfNotSeen(def, EnumInfo(def), result.enums);

  // Sort alphabetically ignorning dialect for ops and section name for
  // sections.
  // TODO: The sorting order could be revised, currently attempting to sort of
  // keep in alphabetical order.
  if (keepOpSourceOrder)
    return result;
  llvm::sort(result.ops, [](const OpDocGroup &lhs, const OpDocGroup &rhs) {
    auto getDesc = [](const OpDocGroup &arg) -> StringRef {
      if (!arg.summary.empty())
        return arg.summary;
      return arg.ops.front().getDef().getValueAsString("opName");
    };
    return getDesc(lhs).compare_insensitive(getDesc(rhs)) < 0;
  });

  return result;
}

//===----------------------------------------------------------------------===//
// Gen Registration
//===----------------------------------------------------------------------===//

static mlir::GenRegistration
    genAttrRegister("gen-attrdef-doc",
                    "Generate dialect attribute documentation",
                    [](const RecordKeeper &records, raw_ostream &os) {
                      if (auto filtered = collectRecords(records))
                        return emitAttrDefDoc(*filtered, os);
                      return true;
                    });

static mlir::GenRegistration
    genOpRegister("gen-op-doc", "Generate dialect documentation",
                  [](const RecordKeeper &records, raw_ostream &os) {
                    if (auto filtered = collectRecords(records))
                      return emitOpDoc(*filtered, os);
                    return true;
                  });

static mlir::GenRegistration
    genTypeRegister("gen-typedef-doc", "Generate dialect type documentation",
                    [](const RecordKeeper &records, raw_ostream &os) {
                      if (auto filtered = collectRecords(records))
                        return emitTypeDefDoc(*filtered, os);
                      return true;
                    });

static mlir::GenRegistration
    genEnumRegister("gen-enum-doc", "Generate dialect enum documentation",
                    [](const RecordKeeper &records, raw_ostream &os) {
                      if (auto filtered = collectRecords(records))
                        return emitEnumDoc(*filtered, os);
                      return true;
                    });

static mlir::GenRegistration
    genRegister("gen-dialect-doc", "Generate dialect documentation",
                [](const RecordKeeper &records, raw_ostream &os) {
                  if (auto filtered = collectRecords(records))
                    return emitDialectDoc(*filtered, os);
                  return true;
                });
